Rework of timeout errors (part 3): extend all raised timeout exceptions with HTTPI::TimeoutError
savonrb/httpi pull request #198
Opened 2018-08-27 08:02 UTC by 907th

2018-08-27 19:44 UTC, rogerleite commented
Waiting for release 2.4.4 be published before merging this PR.

2021-10-06 03:08 UTC, ioquatix requested changes

2021-10-06 03:08 UTC, ioquatix commented on lib/httpi/adapter/em_http.rb
> +        $!.extend TimeoutError
It's better to just raise a new exception and if you want to know the source, use `Exception#cause`.

2021-10-06 03:08 UTC, ioquatix commented
Can you please consider the feedback and rebase this on master? Thanks!

2023-12-02 07:45 UTC, 907th commented
I'm closing stale issue.

2023-12-02 07:45 UTC, closed without merging